#!/usr/bin/env python3
"""Render Civic Agent source coverage documentation from checked-in source cards."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TAXONOMY_PATH = ROOT / "docs" / "coverage-taxonomy.md"
OUTPUT_PATH = ROOT / "docs" / "coverage-matrix.md"
SOURCE_ROOT = ROOT / "jurisdictions"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render Civic Agent coverage docs.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify docs/coverage-matrix.md is current without writing.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    taxonomy = parse_taxonomy(TAXONOMY_PATH)
    cards = load_source_cards()
    content = render_markdown(taxonomy, cards)
    if args.check:
        existing = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.is_file() else None
        if existing != content:
            print("Coverage matrix is out of date. Run `python3 scripts/coverage.py`.")
            raise SystemExit(1)
        print("Coverage matrix is current.")
        return
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print("Rendered docs/coverage-matrix.md.")


def load_source_cards() -> list[dict]:
    cards = []
    for path in sorted(SOURCE_ROOT.glob("*/sources/*.source.json")):
        with path.open(encoding="utf-8") as handle:
            card = json.load(handle)
        card["_path"] = path.relative_to(ROOT).as_posix()
        cards.append(card)
    return cards


def parse_taxonomy(path: Path) -> dict[str, list[dict[str, str]]]:
    active = []
    backlog = []
    for cells in markdown_table_rows(path):
        if len(cells) < 2:
            continue
        if cells[1] == "active" and len(cells) >= 4:
            active.append(
                {
                    "key": cells[0],
                    "label": cells[2],
                    "focus": cells[3],
                }
            )
        elif cells[1] == "backlog" and len(cells) >= 4:
            backlog.append(
                {
                    "key": cells[0],
                    "questions": cells[2],
                    "common_sources": cells[3],
                }
            )
    return {"active": active, "backlog": backlog}


def markdown_table_rows(path: Path) -> list[list[str]]:
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped.startswith("|") or "---" in stripped:
            continue
        rows.append([cell.strip().strip("`") for cell in stripped.strip("|").split("|")])
    return rows


def render_markdown(taxonomy: dict[str, list[dict[str, str]]], cards: list[dict]) -> str:
    lines = [
        "# Civic Agent Coverage Matrix",
        "",
        "Generated by `python3 scripts/coverage.py` from `docs/coverage-taxonomy.md` and checked-in source cards. Do not hand-edit this file.",
        "",
        "Coverage is source-scoped. A supported row means a reviewed source can answer the listed category at the stated measures, grains, and time/version boundary. An unsupported row means unsupported by the reviewed source, not unavailable in the jurisdiction.",
        "",
        "## Active Categories",
        "",
        "| Category | Label | Current focus |",
        "|---|---|---|",
    ]
    for category in taxonomy["active"]:
        lines.append(
            f"| `{escape_cell(category['key'])}` | {escape_cell(category['label'])} | {escape_cell(category['focus'])} |"
        )

    lines.extend(
        [
            "",
            "## Source Coverage Claims",
            "",
            "| Jurisdiction | Source | Category | Status | Measures | Grains | Time/version | Semantics | Evidence | Limits and caveats |",
            "|---|---|---|---|---|---|---|---|---|---|",
        ]
    )
    source_rows = source_claim_rows(cards)
    if source_rows:
        lines.extend(source_rows)
    else:
        lines.append("| - | - | - | No reviewed source-level coverage claims. | - | - | - | - | - | - |")

    lines.extend(
        [
            "",
            "## Jurisdiction Rollup",
            "",
            "This rollup is derived from reviewed source-card claims. It is not a score and should not be read as a statement that the jurisdiction has or lacks data outside reviewed sources.",
            "",
            "| Jurisdiction | Category | Rollup status | Reviewed sources | Notes |",
            "|---|---|---|---|---|",
        ]
    )
    lines.extend(jurisdiction_rollup_rows(cards, taxonomy["active"]))

    lines.extend(
        [
            "",
            "## Backlog Families",
            "",
            "Backlog families are part of the full civic coverage map. They remain not-yet-probed in this source-card matrix until an official source probe promotes a specific category; a separate probe artifact may exist before acceptance.",
            "",
            "| Jurisdiction | Backlog family | Rollup status | Common source types |",
            "|---|---|---|---|",
        ]
    )
    lines.extend(backlog_rows(cards, taxonomy["backlog"]))
    return "\n".join(lines) + "\n"


def source_claim_rows(cards: list[dict]) -> list[str]:
    rows = []
    for card in sorted(cards, key=lambda c: (c["jurisdiction_id"], c["id"])):
        for claim in card.get("coverage_claims", []):
            rows.append(
                "| "
                + " | ".join(
                    [
                        escape_cell(card["jurisdiction_name"]),
                        f"`{escape_cell(card['id'])}`",
                        f"`{escape_cell(claim['category'])}`",
                        f"`{escape_cell(claim['status'])}`",
                        escape_cell(join_values(claim.get("measures", []))),
                        escape_cell(join_values(claim.get("grains", []))),
                        escape_cell(claim.get("time_coverage", "-")),
                        escape_cell(semantics_summary(claim)),
                        escape_cell(join_values(claim.get("evidence", []))),
                        escape_cell(claim_limits(claim)),
                    ]
                )
                + " |"
            )
    return rows


def jurisdiction_rollup_rows(cards: list[dict], active_categories: list[dict[str, str]]) -> list[str]:
    rows = []
    cards_by_jurisdiction: dict[str, list[dict]] = {}
    for card in cards:
        for jurisdiction in card_rollup_jurisdictions(card):
            cards_by_jurisdiction.setdefault(jurisdiction["jurisdiction_id"], []).append(card)

    for jurisdiction_id in sorted(cards_by_jurisdiction):
        jurisdiction_cards = sorted(cards_by_jurisdiction[jurisdiction_id], key=lambda c: c["id"])
        jurisdiction_name = rollup_jurisdiction_name(jurisdiction_id, jurisdiction_cards)
        for category in active_categories:
            claims = [
                (card, claim)
                for card in jurisdiction_cards
                for claim in card.get("coverage_claims", [])
                if claim["category"] == category["key"]
            ]
            status, sources, notes = rollup_status(claims)
            rows.append(
                "| "
                + " | ".join(
                    [
                        escape_cell(jurisdiction_name),
                        f"`{escape_cell(category['key'])}`",
                        f"`{escape_cell(status)}`",
                        escape_cell(join_values(sources) if sources else "-"),
                        escape_cell(notes),
                    ]
                )
                + " |"
            )
    return rows


def rollup_status(claims: list[tuple[dict, dict]]) -> tuple[str, list[str], str]:
    if not claims:
        return "not-yet-probed", [], "No reviewed source card claim."

    reviewed_sources = [card["id"] for card, _ in claims]
    supported = [card["id"] for card, claim in claims if claim["status"] == "supported"]
    if supported:
        return "supported", reviewed_sources, "At least one reviewed source supports this category."

    partial = [card["id"] for card, claim in claims if claim["status"] == "partial"]
    if partial:
        return "partial", reviewed_sources, "At least one reviewed source partially supports this category."

    unsupported = [card["id"] for card, claim in claims if claim["status"] == "unsupported"]
    return (
        "unsupported-by-reviewed-source",
        unsupported,
        "Reviewed source claim is source-scoped; probe another official source before treating this as unavailable.",
    )


def backlog_rows(cards: list[dict], backlog_families: list[dict[str, str]]) -> list[str]:
    rows = []
    jurisdictions = sorted(
        {
            (jurisdiction["jurisdiction_id"], jurisdiction["jurisdiction_name"])
            for card in cards
            for jurisdiction in card_rollup_jurisdictions(card)
        }
    )
    for _, jurisdiction_name in jurisdictions:
        for family in backlog_families:
            rows.append(
                "| "
                + " | ".join(
                    [
                        escape_cell(jurisdiction_name),
                        f"`{escape_cell(family['key'])}`",
                        "`not-yet-probed`",
                        escape_cell(family["common_sources"]),
                    ]
                )
                + " |"
            )
    return rows


def card_rollup_jurisdictions(card: dict) -> list[dict[str, str]]:
    jurisdictions = card.get("coverage_jurisdictions")
    if jurisdictions:
        return jurisdictions
    return [
        {
            "jurisdiction_id": card["jurisdiction_id"],
            "jurisdiction_name": card["jurisdiction_name"],
        }
    ]


def rollup_jurisdiction_name(jurisdiction_id: str, cards: list[dict]) -> str:
    for card in cards:
        for jurisdiction in card_rollup_jurisdictions(card):
            if jurisdiction["jurisdiction_id"] == jurisdiction_id:
                return jurisdiction["jurisdiction_name"]
    return cards[0]["jurisdiction_name"]


def claim_limits(claim: dict) -> str:
    values = []
    unsupported_reason = claim.get("unsupported_reason")
    if unsupported_reason:
        values.append(unsupported_reason)
    values.extend(claim.get("caveats", []))
    return join_values(values) if values else "-"


def semantics_summary(claim: dict) -> str:
    semantics = claim.get("semantics")
    if not semantics:
        return "-"
    summary_fields = [
        "denominator_basis",
        "amount_basis",
        "budget_frame",
        "period_type",
        "period_status",
        "unit",
        "government_scope",
        "geography_basis",
    ]
    parts = [
        f"{field}={semantics[field]}"
        for field in summary_fields
        if semantics.get(field)
    ]
    notes = semantics.get("comparability_notes", [])
    if notes:
        parts.append(f"comparability_notes={join_values(notes)}")
    return "; ".join(parts) if parts else "-"


def join_values(values: list[str]) -> str:
    return "; ".join(str(value) for value in values) if values else "-"


def escape_cell(value: str) -> str:
    return str(value).replace("\n", " ").replace("|", "\\|")


if __name__ == "__main__":
    main()
